model:
  arch: "db_resnet50"
  optimizer: "adamw"
  lr: !!float 1e-3
  weight_decay: !!float 0.01
  rotation: true
  eval_straight: false

data:
  input_size: 1024
  batch_size: 2
  num_workers: 4

trainer:
  precision: 16
  gradient_clip_val: 5.0
  max_epochs: 10
  log_every_n_steps: 100
  resume_from_checkpoint: null
  limit_val_batches: 1.0
  fast_dev_run: 0
